### PR TITLE
Ian version

### PR DESCRIPTION
**Pull request by Stormy110**

### CODE REVIEW

**Review by shoel-uddin — APPROVED** [review]
This looks good

**Review by shoel-uddin — COMMENTED** [review]
why did the package-lock.josn file get changed?

**Comment by Stormy110** [comment]
Im not sure...all I did was git pull npm install and then added the templates and stuff, I double checked to see if the app still works correctly once I noticed the package-lock.json changes and it still does. The node_modules and package.json are all still good as well.

**Review by k5tuck — APPROVED** [review]
Think everything looks good

**Pull request merged**
